### ISSUE TITLE
Run time error in server side

### ISSUE THREAD

**Issue by ac1982** [yinghualuowu/Python_VLPR#1]
Traceback (most recent call last):
  File "main_VLPR.py", line 206, in <module>
    win = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by yinghualuowu** [comment]
还没遇见这种错误。找到了相关链接你可以参考一下https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable
