### ISSUE TITLE
老哥关于重新训练时的问题

### ISSUE THREAD

**Issue by hpyperry** [yinghualuowu/Python_VLPR#10]
: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\modules\ml\src\data.cpp:259: error: (-215) samples.type() == 5 || samples.type() == 4 in function cv::ml::TrainDataImpl::setData
 我的环境是 3.7 opencv 3.4.1 移除dat文件后 重新训练会出现这种错误，请问是啥原因

**Comment by yinghualuowu** [comment]
我随便查了一下
https://github.com/hamuchiwa/AutoRCCar/issues/20
https://stackoverflow.com/questions/49994760/opencv-assertion-failed-in-function-setdata
应该和数据样本有关，但我现在已经不会这些东西了
