### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by blankbird** [yinghualuowu/Python_VLPR#11]
选择照片之后就跑不动了 提示 ValueError: too many values to unpack (expected 2)
小白一个，求指导一下，想先跑起来
![image](https://user-images.githubusercontent.com/33627090/64703075-4eb7b000-d4de-11e9-9291-46ce97f1e23d.png)

**Comment by yinghualuowu** [comment]
看报错应该是 findcontours原因。检查版本
