### ISSUE TITLE
图片无法识别

### ISSUE THREAD

**Issue by sbuygwbw** [yinghualuowu/Python_VLPR#9]
就随便放的两张图片
![A41CE3D0A73583EDC396AF56A94445AB](https://user-images.githubusercontent.com/51234853/58705432-c6574880-83e1-11e9-8ce3-2513d48f6553.png)

![C3728E66C27899390B3A0A77572113F0](https://user-images.githubusercontent.com/51234853/58705452-d707be80-83e1-11e9-8233-61e8b6c455d4.png)

**Comment by yinghualuowu** [comment]
- 这两个没有识别，我感觉挺正常的。
- 第一张过近了。导致一个array的size为空，报异常了，即使continue掉了，最后也被过滤掉，认为不符合规范
- 第二张没有异常，个人认为把图片放大可能会识别出来

**Comment by xiaokun12** [comment]
楼主，请问你的毕业设计python-opencv的车牌识别程序中，svm和svmchinese两个dat文件单独的训练代码可以帮忙发我一份吗？新手学习，不胜感激。我的邮箱ckhuang66@163.com
